#person:
#  lastName: hello
#  age: 18
#  boss: false
#  birthday: 2012/11/14
#  maps: {k1: v1, k2: v2}
#  lists:
#    - Lisi
#    - Zhaoliu
#  dog:
#    name: wangcai
#    age: 4

server:
  port: 8080
spring:
  profiles:
    active: dev

---
server:
  port: 8081
spring:
  profiles: dev

---
server:
  port: 8083
spring:
  profiles: prod